# Generated by Django 2.1.1 on 2022-04-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cmtid', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='cmtid')),
                ('postid', models.PositiveIntegerField(db_index=True, verbose_name='postid')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('text', models.TextField(verbose_name='text')),
            ],
        ),
    ]
