# Generated by Django 2.1.1 on 2022-06-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_remove_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='screened',
            field=models.BooleanField(default=False, verbose_name='screened'),
        ),
    ]
