# Generated by Django 2.1.1 on 2022-07-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_comment_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date'),
        ),
    ]
